-- P0: explicit, auditable paper execution costs.
-- Runtime activation remains behind PAPER_COST_MODEL_ENABLED.

alter table public.paper_trades
  add column if not exists entry_fee_sol numeric not null default 0,
  add column if not exists exit_fee_sol numeric not null default 0,
  add column if not exists slippage_sol numeric not null default 0,
  add column if not exists gross_pnl_sol numeric not null default 0,
  add column if not exists cost_model_version text;

alter table public.shadow_trades
  add column if not exists entry_fee_sol numeric not null default 0,
  add column if not exists exit_fee_sol numeric not null default 0,
  add column if not exists slippage_sol numeric not null default 0,
  add column if not exists gross_pnl_sol numeric not null default 0,
  add column if not exists cost_model_version text;

alter table public.tiered_trades
  add column if not exists entry_fee_sol numeric not null default 0,
  add column if not exists exit_fee_sol numeric not null default 0,
  add column if not exists slippage_sol numeric not null default 0,
  add column if not exists gross_pnl_sol numeric not null default 0,
  add column if not exists cost_model_version text;

alter table public.paper_positions
  add column if not exists entry_fee_sol numeric not null default 0,
  add column if not exists entry_slippage_sol numeric not null default 0,
  add column if not exists entry_liquidity_usd numeric,
  add column if not exists cost_model_version text;

alter table public.shadow_positions
  add column if not exists entry_fee_sol numeric not null default 0,
  add column if not exists entry_slippage_sol numeric not null default 0,
  add column if not exists entry_liquidity_usd numeric,
  add column if not exists cost_model_version text;

alter table public.tiered_positions
  add column if not exists entry_fee_sol numeric not null default 0,
  add column if not exists entry_slippage_sol numeric not null default 0,
  add column if not exists entry_liquidity_usd numeric,
  add column if not exists cost_model_version text;

create table if not exists public.paper_failed_entries (
  id bigint generated by default as identity primary key,
  strategy text not null check (strategy in ('MAIN','SHADOW','TIERED','SCALP')),
  mint text not null,
  token_symbol text not null,
  attempted_size_sol numeric not null check (attempted_size_sol > 0),
  liquidity_usd numeric not null check (liquidity_usd > 0),
  network_fee_sol numeric not null check (network_fee_sol >= 0),
  reason text not null,
  cost_model_version text not null,
  cost_snapshot jsonb not null default '{}'::jsonb,
  happened_at timestamptz not null default now()
);

create index if not exists paper_failed_entries_strategy_time_idx
  on public.paper_failed_entries(strategy, happened_at desc);
create index if not exists paper_failed_entries_mint_time_idx
  on public.paper_failed_entries(mint, happened_at desc);

comment on column public.paper_trades.pnl_sol is
  'Net realised P&L after entry fee, exit fee and slippage when cost_model_version is populated.';
comment on column public.paper_trades.gross_pnl_sol is
  'Price-only realised P&L before network fees, swap fees and slippage.';

-- New cost-aware overload. The legacy 10-argument function remains available
-- until every deployed worker has moved to this signature.
create or replace function public.tiered_open_position(
  p_mint text,
  p_token_symbol text,
  p_entry_price numeric,
  p_entry_time timestamptz,
  p_size_pct numeric,
  p_entry_alert jsonb,
  p_position_id text,
  p_entry_wallet text,
  p_entry_wallet_trust numeric,
  p_filter_snapshot jsonb,
  p_entry_fee_sol numeric,
  p_entry_slippage_sol numeric,
  p_cost_model_version text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_state public.tiered_state%rowtype;
  v_today date := (timezone('Asia/Jerusalem', now()))::date;
  v_size_sol numeric;
  v_total_debit numeric;
begin
  select * into v_state from public.tiered_state where id = 1 for update;
  if not found then raise exception 'tiered_state row 1 is missing'; end if;

  if v_state.daily_date is distinct from v_today then
    update public.tiered_state
    set daily_date = v_today,
        entries_today = 0,
        daily_realized_pnl_sol = 0,
        consecutive_hard_stops = 0,
        halted = case when coalesce(halt_reason, '') like 'circuit_breaker:%' then false else halted end,
        halt_reason = case when coalesce(halt_reason, '') like 'circuit_breaker:%' then null else halt_reason end,
        updated_at = now()
    where id = 1 returning * into v_state;
  end if;

  if v_state.halted then
    return jsonb_build_object('opened', false, 'reason', 'halted:' || coalesce(v_state.halt_reason, 'unknown'));
  end if;
  if v_state.entries_today >= 12 then
    update public.tiered_state
    set halted = true,
        halt_reason = 'circuit_breaker: maximum 12 daily entries reached',
        updated_at = now()
    where id = 1;
    return jsonb_build_object('opened', false, 'reason', 'daily_entry_limit_reached');
  end if;
  if p_entry_wallet_trust is null or p_entry_wallet_trust < 65 then
    return jsonb_build_object('opened', false, 'reason', 'entry_wallet_trust_below_65');
  end if;
  if p_entry_price is null or p_entry_price <= 0 then
    return jsonb_build_object('opened', false, 'reason', 'invalid_entry_price');
  end if;
  if p_size_pct is null or p_size_pct <= 0 or p_size_pct > 1 then
    return jsonb_build_object('opened', false, 'reason', 'invalid_size_pct');
  end if;
  if coalesce(p_entry_fee_sol, 0) < 0 or coalesce(p_entry_slippage_sol, 0) < 0 then
    return jsonb_build_object('opened', false, 'reason', 'invalid_entry_cost');
  end if;
  if (select count(*) from public.tiered_positions) >= 3 then
    return jsonb_build_object('opened', false, 'reason', 'max_concurrent_positions');
  end if;
  if exists (select 1 from public.tiered_positions where mint = p_mint) then
    return jsonb_build_object('opened', false, 'reason', 'mint_already_open');
  end if;
  if exists (
    select 1 from public.tiered_trades
    where mint = p_mint and happened_at >= now() - interval '4 hours'
  ) then
    return jsonb_build_object('opened', false, 'reason', 'mint_in_4h_cooldown');
  end if;

  v_size_sol := v_state.bankroll_sol * p_size_pct;
  v_total_debit := v_size_sol + coalesce(p_entry_fee_sol, 0) + coalesce(p_entry_slippage_sol, 0);
  if v_size_sol <= 0 or v_total_debit > v_state.bankroll_sol then
    return jsonb_build_object('opened', false, 'reason', 'insufficient_cash_after_costs');
  end if;

  insert into public.tiered_positions (
    mint, token_symbol, entry_price, entry_time, size_sol, remaining_pct,
    peak_multiple, ladder_hits, entry_alert, position_id, realized_pnl_sol,
    entry_wallet, entry_wallet_trust, filter_snapshot, entry_fee_sol,
    entry_slippage_sol, entry_liquidity_usd, cost_model_version
  ) values (
    p_mint, coalesce(nullif(p_token_symbol, ''), 'UNKNOWN'), p_entry_price,
    coalesce(p_entry_time, now()), v_size_sol, 1, 1, '[]'::jsonb,
    coalesce(p_entry_alert, '{}'::jsonb), p_position_id, 0, p_entry_wallet,
    p_entry_wallet_trust, coalesce(p_filter_snapshot, '{}'::jsonb),
    coalesce(p_entry_fee_sol, 0), coalesce(p_entry_slippage_sol, 0),
    nullif((p_filter_snapshot #>> '{price_snapshot,liquidityUsd}')::numeric, 0),
    p_cost_model_version
  );

  update public.tiered_state
  set bankroll_sol = bankroll_sol - v_total_debit,
      entries_today = entries_today + 1,
      updated_at = now()
  where id = 1 returning * into v_state;

  return jsonb_build_object(
    'opened', true,
    'reason', null,
    'position_id', p_position_id,
    'size_sol', v_size_sol,
    'entry_fee_sol', coalesce(p_entry_fee_sol, 0),
    'entry_slippage_sol', coalesce(p_entry_slippage_sol, 0),
    'bankroll_sol', v_state.bankroll_sol,
    'entries_today', v_state.entries_today
  );
exception when unique_violation then
  return jsonb_build_object('opened', false, 'reason', 'duplicate_position');
end;
$$;

-- New cost-aware overload. Entry costs were paid when the position opened;
-- each exit row receives its proportional entry-cost allocation for net P&L.
create or replace function public.tiered_apply_exit(
  p_position_id text,
  p_exit_price numeric,
  p_requested_sold_pct numeric,
  p_reason text,
  p_action_terminal boolean,
  p_peak_multiple numeric,
  p_ladder_hits jsonb,
  p_exit_fee_sol numeric,
  p_exit_slippage_sol numeric,
  p_cost_model_version text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_state public.tiered_state%rowtype;
  v_position public.tiered_positions%rowtype;
  v_today date := (timezone('Asia/Jerusalem', now()))::date;
  v_sold_pct numeric;
  v_sold_size_sol numeric;
  v_multiple numeric;
  v_gross_proceeds_sol numeric;
  v_net_proceeds_sol numeric;
  v_gross_pnl_sol numeric;
  v_net_pnl_sol numeric;
  v_allocated_entry_fee numeric;
  v_allocated_entry_slippage numeric;
  v_total_slippage numeric;
  v_remaining_pct numeric;
  v_realized_pnl_sol numeric;
  v_terminal boolean;
  v_daily_pnl numeric;
  v_consecutive_hard_stops integer;
  v_halted boolean;
  v_halt_reason text;
begin
  if p_exit_price is null or p_exit_price <= 0 then
    return jsonb_build_object('applied', false, 'reason', 'invalid_exit_price');
  end if;
  if coalesce(p_exit_fee_sol, 0) < 0 or coalesce(p_exit_slippage_sol, 0) < 0 then
    return jsonb_build_object('applied', false, 'reason', 'invalid_exit_cost');
  end if;

  select * into v_state from public.tiered_state where id = 1 for update;
  if not found then raise exception 'tiered_state row 1 is missing'; end if;

  if v_state.daily_date is distinct from v_today then
    update public.tiered_state
    set daily_date = v_today,
        entries_today = 0,
        daily_realized_pnl_sol = 0,
        consecutive_hard_stops = 0,
        halted = case when coalesce(halt_reason, '') like 'circuit_breaker:%' then false else halted end,
        halt_reason = case when coalesce(halt_reason, '') like 'circuit_breaker:%' then null else halt_reason end,
        updated_at = now()
    where id = 1 returning * into v_state;
  end if;

  select * into v_position
  from public.tiered_positions where position_id = p_position_id for update;
  if not found then return jsonb_build_object('applied', false, 'reason', 'position_not_found'); end if;

  v_sold_pct := least(v_position.remaining_pct, greatest(coalesce(p_requested_sold_pct, 0), 0));
  if v_sold_pct <= 0 then return jsonb_build_object('applied', false, 'reason', 'nothing_to_sell'); end if;

  v_sold_size_sol := v_position.size_sol * v_sold_pct;
  v_multiple := p_exit_price / v_position.entry_price;
  v_gross_proceeds_sol := v_sold_size_sol * v_multiple;
  v_allocated_entry_fee := coalesce(v_position.entry_fee_sol, 0) * v_sold_pct;
  v_allocated_entry_slippage := coalesce(v_position.entry_slippage_sol, 0) * v_sold_pct;
  v_total_slippage := v_allocated_entry_slippage + coalesce(p_exit_slippage_sol, 0);
  v_net_proceeds_sol := v_gross_proceeds_sol - coalesce(p_exit_fee_sol, 0) - coalesce(p_exit_slippage_sol, 0);
  v_gross_pnl_sol := v_gross_proceeds_sol - v_sold_size_sol;
  v_net_pnl_sol := v_gross_pnl_sol - v_allocated_entry_fee - coalesce(p_exit_fee_sol, 0) - v_total_slippage;
  v_remaining_pct := greatest(0, v_position.remaining_pct - v_sold_pct);
  v_realized_pnl_sol := v_position.realized_pnl_sol + v_net_pnl_sol;
  v_terminal := coalesce(p_action_terminal, false) or v_remaining_pct <= 0.001;
  v_daily_pnl := v_state.daily_realized_pnl_sol + v_net_pnl_sol;

  if v_terminal and p_reason = 'hard_stop_loss' then
    v_consecutive_hard_stops := v_state.consecutive_hard_stops + 1;
  elsif v_terminal then
    v_consecutive_hard_stops := 0;
  else
    v_consecutive_hard_stops := v_state.consecutive_hard_stops;
  end if;

  v_halted := v_state.halted;
  v_halt_reason := v_state.halt_reason;
  if not v_state.halted or coalesce(v_state.halt_reason, '') like 'circuit_breaker:%' then
    if v_daily_pnl <= -0.20 then
      v_halted := true;
      v_halt_reason := 'circuit_breaker: daily net realised loss reached -0.20 SOL';
    elsif v_consecutive_hard_stops >= 3 then
      v_halted := true;
      v_halt_reason := 'circuit_breaker: 3 consecutive hard stops';
    end if;
  end if;

  insert into public.tiered_trades (
    token_symbol, mint, type, reason, entry_price, exit_price, multiple,
    sold_pct, sold_size_sol, proceeds_sol, pnl_sol, hold_minutes, happened_at,
    entry_alert, position_id, entry_wallet, entry_fee_sol, exit_fee_sol,
    slippage_sol, gross_pnl_sol, cost_model_version
  ) values (
    v_position.token_symbol, v_position.mint,
    case when v_terminal then 'sell' else 'partial_sell' end,
    p_reason, v_position.entry_price, p_exit_price, v_multiple, v_sold_pct,
    v_sold_size_sol, v_net_proceeds_sol, v_net_pnl_sol,
    extract(epoch from (now() - v_position.entry_time)) / 60, now(),
    v_position.entry_alert, v_position.position_id, v_position.entry_wallet,
    v_allocated_entry_fee, coalesce(p_exit_fee_sol, 0), v_total_slippage,
    v_gross_pnl_sol, p_cost_model_version
  );

  update public.tiered_state
  set bankroll_sol = bankroll_sol + v_net_proceeds_sol,
      daily_realized_pnl_sol = v_daily_pnl,
      consecutive_hard_stops = v_consecutive_hard_stops,
      halted = v_halted,
      halt_reason = v_halt_reason,
      updated_at = now()
  where id = 1 returning * into v_state;

  if v_terminal then
    delete from public.tiered_positions where position_id = p_position_id;
  else
    update public.tiered_positions
    set remaining_pct = v_remaining_pct,
        peak_multiple = greatest(peak_multiple, coalesce(p_peak_multiple, peak_multiple)),
        ladder_hits = coalesce(p_ladder_hits, ladder_hits),
        realized_pnl_sol = v_realized_pnl_sol
    where position_id = p_position_id;
  end if;

  return jsonb_build_object(
    'applied', true,
    'terminal', v_terminal,
    'sold_pct', v_sold_pct,
    'sold_size_sol', v_sold_size_sol,
    'gross_proceeds_sol', v_gross_proceeds_sol,
    'proceeds_sol', v_net_proceeds_sol,
    'gross_pnl_sol', v_gross_pnl_sol,
    'pnl_sol', v_net_pnl_sol,
    'entry_fee_sol', v_allocated_entry_fee,
    'exit_fee_sol', coalesce(p_exit_fee_sol, 0),
    'slippage_sol', v_total_slippage,
    'remaining_pct', v_remaining_pct,
    'bankroll_sol', v_state.bankroll_sol,
    'daily_realized_pnl_sol', v_state.daily_realized_pnl_sol,
    'consecutive_hard_stops', v_state.consecutive_hard_stops,
    'halted', v_state.halted,
    'halt_reason', v_state.halt_reason
  );
end;
$$;

create or replace function public.tiered_charge_failed_entry(
  p_mint text,
  p_token_symbol text,
  p_attempted_size_sol numeric,
  p_liquidity_usd numeric,
  p_network_fee_sol numeric,
  p_cost_model_version text,
  p_cost_snapshot jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_state public.tiered_state%rowtype;
begin
  if p_network_fee_sol is null or p_network_fee_sol < 0 then
    return jsonb_build_object('charged', false, 'reason', 'invalid_network_fee');
  end if;
  select * into v_state from public.tiered_state where id = 1 for update;
  if not found then raise exception 'tiered_state row 1 is missing'; end if;
  if v_state.bankroll_sol < p_network_fee_sol then
    return jsonb_build_object('charged', false, 'reason', 'insufficient_cash_for_failed_fee');
  end if;

  update public.tiered_state
  set bankroll_sol = bankroll_sol - p_network_fee_sol, updated_at = now()
  where id = 1 returning * into v_state;

  insert into public.paper_failed_entries (
    strategy, mint, token_symbol, attempted_size_sol, liquidity_usd,
    network_fee_sol, reason, cost_model_version, cost_snapshot
  ) values (
    'TIERED', p_mint, coalesce(nullif(p_token_symbol,''),'UNKNOWN'),
    p_attempted_size_sol, p_liquidity_usd, p_network_fee_sol,
    'simulated_entry_transaction_failed', p_cost_model_version,
    coalesce(p_cost_snapshot, '{}'::jsonb)
  );

  return jsonb_build_object('charged', true, 'bankroll_sol', v_state.bankroll_sol);
end;
$$;
