begin;

create extension if not exists pgcrypto;

create table if not exists public.gold_bot_state (
  bot_id text primary key,
  balance_usd numeric(20, 6) not null check (balance_usd >= 0),
  daily_start_balance_usd numeric(20, 6) not null check (daily_start_balance_usd >= 0),
  daily_date date not null,
  paused boolean not null default false,
  pause_reason text,
  last_processed_candle_time timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.gold_paper_positions (
  id uuid primary key default gen_random_uuid(),
  bot_id text not null references public.gold_bot_state(bot_id) on delete cascade,
  instrument text not null,
  side text not null check (side in ('long', 'short')),
  units numeric(24, 8) not null check (units > 0),
  entry_price numeric(20, 8) not null check (entry_price > 0),
  stop_loss numeric(20, 8) not null check (stop_loss > 0),
  take_profit numeric(20, 8) not null check (take_profit > 0),
  entry_spread numeric(20, 8) not null check (entry_spread >= 0),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  exit_price numeric(20, 8),
  realized_pnl_usd numeric(20, 6),
  close_reason text,
  status text not null default 'open' check (status in ('open', 'closed')),
  strategy_version text not null,
  signal_json jsonb,
  check (
    (status = 'open' and closed_at is null and exit_price is null and realized_pnl_usd is null)
    or
    (status = 'closed' and closed_at is not null and exit_price is not null and realized_pnl_usd is not null)
  )
);

create unique index if not exists gold_one_open_position_per_bot
  on public.gold_paper_positions(bot_id)
  where status = 'open';

create index if not exists gold_positions_bot_opened_idx
  on public.gold_paper_positions(bot_id, opened_at desc);

create table if not exists public.gold_bot_events (
  id bigint generated by default as identity primary key,
  bot_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists gold_events_bot_created_idx
  on public.gold_bot_events(bot_id, created_at desc);

alter table public.gold_bot_state enable row level security;
alter table public.gold_paper_positions enable row level security;
alter table public.gold_bot_events enable row level security;

revoke all on table public.gold_bot_state from anon, authenticated;
revoke all on table public.gold_paper_positions from anon, authenticated;
revoke all on table public.gold_bot_events from anon, authenticated;

create or replace function public.close_gold_paper_position(
  p_position_id uuid,
  p_exit_price numeric,
  p_realized_pnl_usd numeric,
  p_close_reason text,
  p_closed_at timestamptz default now()
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bot_id text;
begin
  if p_exit_price is null or p_exit_price <= 0 then
    raise exception 'exit price must be positive';
  end if;
  if p_realized_pnl_usd is null then
    raise exception 'realized PnL is required';
  end if;
  if nullif(trim(p_close_reason), '') is null then
    raise exception 'close reason is required';
  end if;

  update public.gold_paper_positions
  set
    status = 'closed',
    exit_price = p_exit_price,
    realized_pnl_usd = p_realized_pnl_usd,
    close_reason = p_close_reason,
    closed_at = coalesce(p_closed_at, now())
  where id = p_position_id
    and status = 'open'
  returning bot_id into v_bot_id;

  if v_bot_id is null then
    return false;
  end if;

  update public.gold_bot_state
  set
    balance_usd = balance_usd + p_realized_pnl_usd,
    updated_at = now()
  where bot_id = v_bot_id;

  if not found then
    raise exception 'gold bot state not found for %', v_bot_id;
  end if;

  insert into public.gold_bot_events(bot_id, event_type, payload)
  values (
    v_bot_id,
    'position_closed',
    jsonb_build_object(
      'positionId', p_position_id,
      'exitPrice', p_exit_price,
      'realizedPnlUsd', p_realized_pnl_usd,
      'reason', p_close_reason,
      'closedAt', coalesce(p_closed_at, now())
    )
  );

  return true;
end;
$$;

revoke all on function public.close_gold_paper_position(uuid, numeric, numeric, text, timestamptz)
  from public, anon, authenticated;
grant execute on function public.close_gold_paper_position(uuid, numeric, numeric, text, timestamptz)
  to service_role;

commit;
