create table if not exists public.token_intelligence_snapshots (
  id bigint generated by default as identity primary key,
  mint text not null,
  symbol text,
  pair_address text,
  observed_at timestamptz not null default now(),
  mode text not null default 'shadow',
  recommendation text,
  snapshot jsonb not null default '{}'::jsonb
);
create index if not exists token_intelligence_snapshots_mint_observed_idx on public.token_intelligence_snapshots (mint, observed_at desc);

create table if not exists public.helius_credit_usage (
  id bigint generated by default as identity primary key,
  service text not null,
  operation text not null,
  mint text,
  estimated_credits integer not null default 1 check (estimated_credits >= 0),
  created_at timestamptz not null default now()
);
create index if not exists helius_credit_usage_created_idx on public.helius_credit_usage (created_at desc);

create table if not exists public.intelligence_worker_state (
  service text primary key,
  mode text not null default 'off',
  status text not null default 'inactive',
  hourly_credits bigint not null default 0,
  daily_credits bigint not null default 0,
  monthly_credits bigint not null default 0,
  last_heartbeat_at timestamptz,
  details jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.token_intelligence_snapshots enable row level security;
alter table public.helius_credit_usage enable row level security;
alter table public.intelligence_worker_state enable row level security;

comment on table public.token_intelligence_snapshots is 'Observation-only Helius intelligence. Never read by live execution in v1.';
comment on table public.helius_credit_usage is 'Estimated local Helius credit ledger used for circuit breakers.';
comment on table public.intelligence_worker_state is 'Heartbeat and budget state for the isolated intelligence Railway service.';
