alter table public.wallet_lab_candidates
  add column if not exists last_signature text;

create table if not exists public.wallet_lab_transactions (
  id bigint generated by default as identity primary key,
  wallet_address text not null references public.wallet_lab_candidates(wallet_address) on delete cascade,
  signature text not null,
  token_mint text not null,
  side text not null,
  sol_amount numeric not null,
  token_amount numeric not null default 0,
  tx_time timestamptz not null,
  is_scalp boolean not null default false,
  created_at timestamptz not null default now(),
  constraint wallet_lab_transactions_side_check check (side in ('buy','sell')),
  constraint wallet_lab_transactions_unique unique(wallet_address, signature, token_mint, side)
);

create index if not exists wallet_lab_transactions_wallet_time_idx
  on public.wallet_lab_transactions(wallet_address, tx_time desc);
create index if not exists wallet_lab_transactions_token_time_idx
  on public.wallet_lab_transactions(token_mint, tx_time desc);

alter table public.wallet_lab_transactions enable row level security;
