create table if not exists public.wallet_lab_candidates (
  wallet_address text primary key,
  source text not null default 'gmgn_smart_money_7d',
  status text not null default 'observing',
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  observation_count integer not null default 1,
  leaderboard_score numeric not null default 0,
  leaderboard_metrics jsonb not null default '{}'::jsonb,
  final_profile jsonb,
  lab_trust_score numeric,
  profiled_at timestamptz,
  qualified_at timestamptz,
  rejected_at timestamptz,
  rejection_reasons text[] not null default '{}',
  promoted_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint wallet_lab_candidates_status_check check (
    status in ('observing','profile_pending','qualified','rejected','trial','disabled')
  )
);

create table if not exists public.wallet_lab_observations (
  id bigint generated by default as identity primary key,
  wallet_address text not null references public.wallet_lab_candidates(wallet_address) on delete cascade,
  captured_at timestamptz not null default now(),
  leaderboard_score numeric not null default 0,
  metrics jsonb not null default '{}'::jsonb
);

create table if not exists public.wallet_lab_runs (
  id bigint generated by default as identity primary key,
  status text not null,
  fetched_count integer not null default 0,
  unique_count integer not null default 0,
  observed_count integer not null default 0,
  profiled_count integer not null default 0,
  qualified_count integer not null default 0,
  rejected_count integer not null default 0,
  helius_calls integer not null default 0,
  notes jsonb not null default '{}'::jsonb,
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.lab_strategy_state (
  variant text primary key,
  bankroll_sol numeric not null default 10,
  starting_bankroll_sol numeric not null default 10,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint lab_strategy_state_variant_check check (variant in ('shadow','legion'))
);

insert into public.lab_strategy_state (variant, bankroll_sol, starting_bankroll_sol, enabled)
values ('shadow', 10, 10, true), ('legion', 10, 10, true)
on conflict (variant) do nothing;

create table if not exists public.lab_positions (
  variant text not null,
  mint text not null,
  token_symbol text not null,
  entry_price numeric not null,
  entry_time timestamptz not null,
  size_sol numeric not null,
  remaining_pct numeric not null default 1,
  peak_multiple numeric not null default 1,
  ladder_hits numeric[] not null default '{}',
  entry_alert jsonb not null default '{}'::jsonb,
  position_id text not null,
  realized_pnl_sol numeric not null default 0,
  updated_at timestamptz not null default now(),
  primary key (variant, mint),
  constraint lab_positions_variant_check check (variant in ('shadow','legion'))
);

create table if not exists public.lab_trades (
  id bigint generated by default as identity primary key,
  variant text not null,
  position_id text not null,
  token_symbol text not null,
  mint text not null,
  type text not null default 'sell',
  reason text not null,
  entry_price numeric not null,
  exit_price numeric not null,
  multiple numeric not null,
  sold_pct numeric not null,
  pnl_sol numeric not null,
  hold_minutes numeric not null default 0,
  happened_at timestamptz not null default now(),
  entry_alert jsonb not null default '{}'::jsonb,
  constraint lab_trades_variant_check check (variant in ('shadow','legion'))
);

create table if not exists public.wallet_lab_signals (
  id bigint generated by default as identity primary key,
  token_mint text not null,
  token_symbol text not null,
  wallets_count integer not null,
  total_sol_bought numeric not null,
  score integer not null,
  market_cap_usd numeric not null,
  liquidity_usd numeric not null,
  average_trust_score numeric not null,
  participants jsonb not null default '[]'::jsonb,
  alert jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists wallet_lab_candidates_status_score_idx
  on public.wallet_lab_candidates(status, leaderboard_score desc);
create index if not exists wallet_lab_candidates_first_seen_idx
  on public.wallet_lab_candidates(first_seen_at);
create index if not exists wallet_lab_observations_wallet_time_idx
  on public.wallet_lab_observations(wallet_address, captured_at desc);
create index if not exists wallet_lab_runs_started_idx
  on public.wallet_lab_runs(started_at desc);
create index if not exists lab_positions_variant_time_idx
  on public.lab_positions(variant, entry_time desc);
create index if not exists lab_trades_variant_time_idx
  on public.lab_trades(variant, happened_at desc);
create index if not exists wallet_lab_signals_mint_time_idx
  on public.wallet_lab_signals(token_mint, created_at desc);

alter table public.wallet_lab_candidates enable row level security;
alter table public.wallet_lab_observations enable row level security;
alter table public.wallet_lab_runs enable row level security;
alter table public.lab_strategy_state enable row level security;
alter table public.lab_positions enable row level security;
alter table public.lab_trades enable row level security;
alter table public.wallet_lab_signals enable row level security;
