create table if not exists public.ai_paper_learning_runs (
  id bigint generated by default as identity primary key,
  model_version text not null,
  sample_size integer not null default 0,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_paper_learning_segments (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.ai_paper_learning_runs(id) on delete cascade,
  segment_key text not null,
  sample_size integer not null default 0,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(run_id, segment_key)
);

create index if not exists ai_paper_learning_runs_created_at_idx on public.ai_paper_learning_runs (created_at desc);
create index if not exists ai_paper_learning_segments_run_idx on public.ai_paper_learning_segments (run_id);

alter table public.ai_paper_learning_runs enable row level security;
alter table public.ai_paper_learning_segments enable row level security;

comment on table public.ai_paper_learning_runs is 'Analytics generated from completed paper trades; no live execution or automatic strategy changes.';
