-- Moonshot Phase 1: observation-only market scanner.
-- This migration creates no trade execution path and does not modify Legion data.

create table if not exists public.moonshot_scanner_state (
  id smallint primary key default 1 check (id = 1),
  version text not null default 'moonshot_scanner_v1_2026_07_27',
  mode text not null default 'scanner_only' check (mode = 'scanner_only'),
  enabled boolean not null default false,
  status text not null default 'disabled',
  program_ids text[] not null default '{}'::text[],
  active_subscriptions integer not null default 0,
  queue_depth integer not null default 0,
  events_received bigint not null default 0,
  events_dropped bigint not null default 0,
  transaction_fetch_failures bigint not null default 0,
  candidates_recorded bigint not null default 0,
  last_event_at timestamptz,
  last_candidate_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);

insert into public.moonshot_scanner_state (
  id,
  enabled,
  status
)
values (1, false, 'disabled')
on conflict (id) do nothing;

create table if not exists public.moonshot_candidates (
  id bigint generated by default as identity primary key,
  signature text not null,
  program_id text not null,
  slot bigint not null,
  mint text not null,
  received_at timestamptz not null,
  detected_at timestamptz not null default now(),
  block_time timestamptz,
  latency_ms integer,
  sequence_status text not null default 'observed',
  rug_gate_status text not null default 'not_run',
  would_enter boolean not null default false,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint moonshot_candidates_signature_program_mint_key
    unique (signature, program_id, mint),
  constraint moonshot_candidates_scanner_only_check
    check (would_enter = false)
);

create index if not exists moonshot_candidates_detected_at_idx
  on public.moonshot_candidates (detected_at desc);

create index if not exists moonshot_candidates_mint_detected_at_idx
  on public.moonshot_candidates (mint, detected_at desc);

create index if not exists moonshot_candidates_program_detected_at_idx
  on public.moonshot_candidates (program_id, detected_at desc);

alter table public.moonshot_scanner_state enable row level security;
alter table public.moonshot_candidates enable row level security;

revoke all on table public.moonshot_scanner_state from anon, authenticated;
revoke all on table public.moonshot_candidates from anon, authenticated;

grant select, insert, update, delete on table public.moonshot_scanner_state to service_role;
grant select, insert, update, delete on table public.moonshot_candidates to service_role;
grant usage, select on sequence public.moonshot_candidates_id_seq to service_role;

comment on table public.moonshot_scanner_state is
  'Moonshot scanner health only. Phase 1 cannot create paper or live trades.';

comment on table public.moonshot_candidates is
  'Moonshot raw candidate observations. would_enter is constrained false during Phase 1.';
