-- Symbol-level cooldown after a catastrophic AI Discovery rug.
-- This is deliberately narrow: only realized returns <= -90% trigger it.
-- It does not block ordinary losses and it never keys cooldowns by mint.

create table if not exists public.ai_symbol_rug_cooldown_config (
  id smallint primary key default 1 check (id = 1),
  cooldown_hours integer not null default 24 check (cooldown_hours between 1 and 168),
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.ai_symbol_rug_cooldown_config (id, cooldown_hours, enabled)
values (1, 24, true)
on conflict (id) do nothing;

create table if not exists public.ai_symbol_rug_cooldown_blocks (
  id bigint generated by default as identity primary key,
  normalized_symbol text not null,
  candidate_mint text not null,
  rugged_mint text not null,
  rugged_trade_id bigint not null references public.ai_discovery_trades(id) on delete cascade,
  rugged_at timestamptz not null,
  cooldown_until timestamptz not null,
  reason text not null default 'blocked_symbol_rug_cooldown',
  blocked_at timestamptz not null default now(),
  unique (candidate_mint, rugged_trade_id)
);

create index if not exists ai_symbol_rug_cooldown_blocks_symbol_idx
  on public.ai_symbol_rug_cooldown_blocks (normalized_symbol, cooldown_until desc);

alter table public.ai_symbol_rug_cooldown_config enable row level security;
alter table public.ai_symbol_rug_cooldown_blocks enable row level security;

create or replace function public.enforce_ai_symbol_rug_cooldown()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  cfg public.ai_symbol_rug_cooldown_config%rowtype;
  rug record;
  symbol_key text;
begin
  select * into cfg
  from public.ai_symbol_rug_cooldown_config
  where id = 1;

  if not coalesce(cfg.enabled, true) then
    return new;
  end if;

  symbol_key := lower(btrim(coalesce(new.token_symbol, '')));
  if symbol_key = '' then
    return new;
  end if;

  select
    t.id,
    t.mint,
    t.closed_at,
    t.closed_at + make_interval(hours => coalesce(cfg.cooldown_hours, 24)) as cooldown_until
  into rug
  from public.ai_discovery_trades t
  where lower(btrim(coalesce(t.token_symbol, ''))) = symbol_key
    and t.net_return_pct <= -90
    and t.closed_at >= now() - make_interval(hours => coalesce(cfg.cooldown_hours, 24))
  order by t.closed_at desc
  limit 1;

  if rug.id is null then
    return new;
  end if;

  new.status := 'blocked_symbol_rug_cooldown';
  new.risks := coalesce(new.risks, '[]'::jsonb) || jsonb_build_array('blocked_symbol_rug_cooldown');

  insert into public.ai_symbol_rug_cooldown_blocks (
    normalized_symbol,
    candidate_mint,
    rugged_mint,
    rugged_trade_id,
    rugged_at,
    cooldown_until
  ) values (
    symbol_key,
    new.mint,
    rug.mint,
    rug.id,
    rug.closed_at,
    rug.cooldown_until
  )
  on conflict (candidate_mint, rugged_trade_id) do update
  set blocked_at = now(),
      cooldown_until = excluded.cooldown_until;

  return new;
end;
$$;

drop trigger if exists enforce_ai_symbol_rug_cooldown on public.market_opportunities;
create trigger enforce_ai_symbol_rug_cooldown
before insert or update of token_symbol, status, risks
on public.market_opportunities
for each row
execute function public.enforce_ai_symbol_rug_cooldown();

comment on table public.ai_symbol_rug_cooldown_blocks is
  'Audit log for candidate mints suppressed after a same-symbol <= -90% AI Discovery rug.';
