create table if not exists public.lp_lock_shadow_audits (
  id bigint generated by default as identity primary key,
  detector_version text not null,
  subject_type text not null check (subject_type in ('candidate', 'trade')),
  subject_id text not null,
  mint text not null,
  token_symbol text,
  pair_address text,
  source_observed_at timestamptz,
  verdict text not null check (verdict in ('LOCKED', 'UNLOCKED', 'UNKNOWN')),
  method text not null,
  source text not null,
  result jsonb not null default '{}'::jsonb,
  protective_pass boolean,
  created_at timestamptz not null default now(),
  unique (detector_version, subject_type, subject_id)
);

create index if not exists lp_lock_shadow_audits_created_idx
  on public.lp_lock_shadow_audits (created_at desc);
create index if not exists lp_lock_shadow_audits_verdict_idx
  on public.lp_lock_shadow_audits (detector_version, verdict, created_at desc);

comment on table public.lp_lock_shadow_audits is
  'Shadow-only GoPlus/on-chain LP detector audit results. Never used directly to permit or execute trades.';
