create table if not exists public.helius_flow_paper_state (
  service text primary key,
  enabled boolean not null default true,
  starting_bankroll_sol numeric not null default 1,
  cash_sol numeric not null default 1,
  realized_pnl_sol numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.helius_flow_paper_positions (
  position_id uuid primary key default gen_random_uuid(),
  mint text not null unique,
  symbol text,
  pair_address text,
  intelligence_snapshot_id bigint,
  entry_price_usd numeric,
  size_sol numeric not null,
  token_raw_amount text not null,
  entry_value_lamports text not null,
  peak_executable_sol numeric not null,
  last_executable_sol numeric not null,
  opened_at timestamptz not null default now(),
  last_checked_at timestamptz not null default now(),
  entry_snapshot jsonb not null default '{}'::jsonb
);

create table if not exists public.helius_flow_paper_trades (
  id bigint generated by default as identity primary key,
  position_id uuid not null,
  mint text not null,
  symbol text,
  pair_address text,
  intelligence_snapshot_id bigint,
  size_sol numeric not null,
  proceeds_sol numeric not null,
  pnl_sol numeric not null,
  net_return_pct numeric not null,
  exit_reason text not null,
  opened_at timestamptz not null,
  closed_at timestamptz not null default now(),
  entry_snapshot jsonb not null default '{}'::jsonb,
  exit_snapshot jsonb not null default '{}'::jsonb
);

create index if not exists helius_flow_positions_opened_idx on public.helius_flow_paper_positions(opened_at);
create index if not exists helius_flow_trades_closed_idx on public.helius_flow_paper_trades(closed_at desc);

insert into public.helius_flow_paper_state(service, enabled, starting_bankroll_sol, cash_sol, realized_pnl_sol)
values ('helius_flow_paper_v1', true, 1, 1, 0)
on conflict (service) do nothing;
