create table if not exists public.ai_entry_screen_rejections (
  id bigint generated by default as identity primary key,
  mint text not null,
  symbol text,
  check_failed text not null,
  observed_value jsonb,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_entry_screen_rejections_mint_created_idx
  on public.ai_entry_screen_rejections (mint, created_at desc);

create index if not exists ai_entry_screen_rejections_check_created_idx
  on public.ai_entry_screen_rejections (check_failed, created_at desc);
