create table if not exists public.tiered_state (
  id integer primary key default 1,
  bankroll_sol numeric not null default 10,
  starting_bankroll_sol numeric not null default 10,
  halted boolean not null default false,
  halt_reason text,
  updated_at timestamptz not null default now(),
  constraint tiered_state_singleton check (id = 1)
);

insert into public.tiered_state (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.tiered_positions (
  mint text primary key,
  token_symbol text not null,
  entry_price numeric not null,
  entry_time timestamptz not null,
  size_sol numeric not null,
  remaining_pct numeric not null default 1,
  peak_multiple numeric not null default 1,
  ladder_hits jsonb not null default '[]'::jsonb,
  entry_alert jsonb not null default '{}'::jsonb,
  position_id text not null unique,
  realized_pnl_sol numeric not null default 0,
  entry_wallet text not null,
  entry_wallet_trust numeric not null,
  filter_snapshot jsonb not null default '{}'::jsonb
);

create table if not exists public.tiered_trades (
  id bigint generated by default as identity primary key,
  token_symbol text not null,
  mint text not null,
  type text not null,
  reason text not null,
  entry_price numeric not null,
  exit_price numeric not null,
  multiple numeric not null,
  sold_pct numeric not null,
  sold_size_sol numeric not null,
  proceeds_sol numeric not null,
  pnl_sol numeric not null,
  hold_minutes numeric not null,
  happened_at timestamptz not null default now(),
  entry_alert jsonb not null default '{}'::jsonb,
  position_id text not null,
  entry_wallet text not null
);

create index if not exists tiered_trades_mint_time_idx
  on public.tiered_trades (mint, happened_at desc);
create index if not exists tiered_trades_position_idx
  on public.tiered_trades (position_id);

create table if not exists public.tiered_processed_signals (
  id uuid primary key,
  wallet_address text not null,
  token_mint text not null,
  seen_at timestamptz not null default now(),
  entered boolean not null default false,
  skip_reasons text[] not null default '{}'::text[],
  filter_snapshot jsonb not null default '{}'::jsonb,
  unique (wallet_address, token_mint)
);

create index if not exists tiered_processed_seen_idx
  on public.tiered_processed_signals (seen_at desc);
