CREATE TABLE IF NOT EXISTS public.wallet_discovery_rejections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_address text NOT NULL,
  discovery_source text NOT NULL,
  rejection_stage text NOT NULL,
  skip_reasons text[] NOT NULL DEFAULT '{}',
  filter_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS wallet_discovery_rejections_wallet_created_idx
  ON public.wallet_discovery_rejections (wallet_address, created_at DESC);

CREATE INDEX IF NOT EXISTS wallet_discovery_rejections_source_created_idx
  ON public.wallet_discovery_rejections (discovery_source, created_at DESC);
