-- Fail-closed live trading foundation. This migration does not enable execution.
create extension if not exists pgcrypto;

create table if not exists public.live_trading_config (
  id smallint primary key default 1 check (id = 1),
  execution_enabled boolean not null default false,
  emergency_stop boolean not null default true,
  wallet_public_key text,
  max_position_usd numeric not null default 25 check (max_position_usd > 0),
  max_daily_loss_usd numeric not null default 50 check (max_daily_loss_usd > 0),
  max_open_positions integer not null default 1 check (max_open_positions between 1 and 5),
  minimum_wallet_reserve_usd numeric not null default 100 check (minimum_wallet_reserve_usd >= 0),
  max_consecutive_execution_failures integer not null default 2 check (max_consecutive_execution_failures between 1 and 5),
  consecutive_execution_failures integer not null default 0,
  last_health_check_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint live_requires_wallet check (not execution_enabled or wallet_public_key is not null),
  constraint live_requires_stop_off check (not execution_enabled or emergency_stop = false)
);

insert into public.live_trading_config (id) values (1) on conflict (id) do nothing;

create table if not exists public.live_investors (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  email text,
  contributed_usd numeric not null default 0 check (contributed_usd >= 0),
  ownership_units numeric not null default 0 check (ownership_units >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.live_cash_ledger (
  id bigint generated by default as identity primary key,
  investor_id uuid references public.live_investors(id),
  entry_type text not null check (entry_type in ('deposit','withdrawal','fee','realized_pnl','adjustment')),
  amount_usd numeric not null,
  reference text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.live_positions (
  id uuid primary key default gen_random_uuid(),
  mint text not null,
  token_symbol text,
  tx_signature text unique,
  entry_price_usd numeric not null check (entry_price_usd > 0),
  token_quantity numeric not null check (token_quantity > 0),
  cost_usd numeric not null check (cost_usd > 0),
  status text not null default 'open' check (status in ('pending','open','closing','closed','failed')),
  ai_score numeric,
  entry_reason jsonb not null default '{}'::jsonb,
  opened_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.live_trades (
  id bigint generated by default as identity primary key,
  position_id uuid references public.live_positions(id),
  side text not null check (side in ('buy','sell')),
  requested_usd numeric not null check (requested_usd > 0),
  filled_usd numeric check (filled_usd >= 0),
  fee_usd numeric not null default 0 check (fee_usd >= 0),
  slippage_bps numeric,
  tx_signature text unique,
  execution_status text not null check (execution_status in ('submitted','confirmed','failed','expired')),
  error_message text,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz
);

create table if not exists public.live_audit_log (
  id bigint generated by default as identity primary key,
  actor text not null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.live_trading_config enable row level security;
alter table public.live_investors enable row level security;
alter table public.live_cash_ledger enable row level security;
alter table public.live_positions enable row level security;
alter table public.live_trades enable row level security;
alter table public.live_audit_log enable row level security;

-- Service role only by default. No public/member policies are created for live-money data.
comment on table public.live_trading_config is 'Fail-closed live controls. execution_enabled defaults false and emergency_stop defaults true.';
