"use client";
import {useCallback,useEffect,useState} from "react";
type Data={wallet:string;count:number;rawEvents:number;signaturesScanned:number;hasMoreHistory:boolean;stats:any;holdBuckets:any[];trades:any[];mcEnrichment:any[];priceEnrichment:any};
const money=(n:any)=>Number(n??0).toFixed(4),pct=(n:any)=>Number(n??0).toFixed(1),time=(v:any)=>v?new Date(v).toLocaleString("en-IL",{dateStyle:"short",timeStyle:"short"}):"—";
export default function TradeResearchPage(){
 const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[lastScan,setLastScan]=useState("");
 const load=useCallback(async()=>{setError("");const r=await fetch("/api/trade-research?signatures=500",{cache:"no-store"});if(r.status===401){setError("Open the main dashboard and log in first.");return;}const j=await r.json();if(!r.ok){setError(j.error||"Failed to load");return;}setData(j);},[]);
 useEffect(()=>{void load();},[load]);
 async function scan(){setBusy(true);setError("");setLastScan("");try{const r=await fetch("/api/trade-research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({maxSignatures:1000})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Analysis failed");setData(j);setLastScan(`Analyzed ${j.signaturesScanned} transactions → ${j.rawEvents} trade events → ${j.count} completed trades.${j.hasMoreHistory?" More history is available.":""}`);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <main style={s.page}><div style={s.wrap}>
 <header style={s.header}><div><div style={s.kicker}>SOLANA TRADE LAB</div><h1 style={s.h1}>Your Trading History</h1><p style={s.muted}>Direct on-chain analysis — this version does not depend on Supabase.</p></div><button style={s.button} onClick={scan} disabled={busy}>{busy?"ANALYZING…":"ANALYZE 1,000 TRANSACTIONS"}</button></header>
 {error&&<div style={s.error}>{error}</div>}{lastScan&&<div style={s.success}>{lastScan}</div>}
 {data&&<><div style={s.wallet}><b>Wallet</b><code>{data.wallet}</code><span>{data.rawEvents} swap events • {data.count} reconstructed trades • {data.signaturesScanned} transactions scanned</span></div>
 <section style={s.grid}><Card t="Win rate" v={pct(data.stats.winRate*100)+"%"} /><Card t="Realized P&L" v={money(data.stats.pnlSol)+" SOL"} /><Card t="Profit factor" v={data.stats.profitFactor==null?"—":Number(data.stats.profitFactor).toFixed(2)} /><Card t="Expectancy" v={money(data.stats.expectancySol)+" SOL"} /><Card t="Max drawdown" v={money(data.stats.maxDrawdownSol)+" SOL"} /><Card t="Avg hold" v={pct(data.stats.avgHoldMinutes)+" min"} /><Card t="Wins / losses" v={data.stats.wins+" / "+data.stats.losses} /><Card t="Worst streak" v={String(data.stats.maxLossStreak)} /></section>
 <section style={s.card}><h2>What your holding time is doing</h2><table><thead><tr><th>Hold time</th><th>Trades</th><th>Win rate</th><th>Avg ROI</th><th>P&L SOL</th></tr></thead><tbody>{data.holdBuckets.map((b:any,i:number)=><tr key={i}><td>{b.label}</td><td>{b.trades}</td><td>{pct(b.winRate*100)}%</td><td>{pct(b.avgRoi)}%</td><td>{money(b.pnlSol)}</td></tr>)}</tbody></table></section>
 <section style={s.card}><h2>Recent reconstructed trades</h2><div style={s.scroll}><table><thead><tr><th>Token</th><th>Entry</th><th>Exit</th><th>Hold</th><th>Entry SOL</th><th>P&L</th><th>ROI</th><th>Result</th></tr></thead><tbody>{data.trades.map((t:any,i:number)=><tr key={i}><td><code>{String(t.tokenMint).slice(0,8)}…</code></td><td>{time(t.entryTime)}</td><td>{time(t.exitTime)}</td><td>{Math.round(Number(t.holdSeconds)/60)}m</td><td>{money(t.entrySol)}</td><td>{money(t.pnlSol)}</td><td>{pct(t.roiPct)}%</td><td>{t.outcome}</td></tr>)}</tbody></table></div></section>
 <section style={s.card}><h2>Next layer: market context</h2><p style={s.muted}>On-chain P&L is live now. Historical market cap, token ATH after entry, maximum run-up/drawdown and “how much more the token moved after you sold” require historical token-price/candle data. We can add that without putting trade data back into Supabase.</p></section>
 </>}</div></main>}
function Card({t,v}:{t:string;v:string}){return <div style={s.card}><small style={s.muted}>{t}</small><strong style={{fontSize:25}}>{v}</strong></div>}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#080d15",color:"#f4f7fb",padding:"24px 14px 60px",fontFamily:"Inter,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif"},wrap:{maxWidth:1150,margin:"0 auto"},header:{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap",alignItems:"flex-start"},kicker:{color:"#8290a5",fontWeight:800,letterSpacing:".12em"},h1:{fontSize:"clamp(32px,7vw,50px)",margin:"6px 0",letterSpacing:"-.04em"},muted:{color:"#8997aa"},button:{border:0,borderRadius:12,padding:"13px 16px",fontWeight:900,background:"#f4f7fb",color:"#080d15"},error:{margin:"16px 0",padding:13,borderRadius:12,border:"1px solid #6b2b38",color:"#ff7b8d"},success:{margin:"16px 0",padding:13,borderRadius:12,border:"1px solid #31543f",color:"#a9e7bc"},wallet:{margin:"18px 0",padding:14,borderRadius:14,border:"1px solid #223149",background:"#111a27",display:"flex",gap:12,flexWrap:"wrap",alignItems:"center"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:10},card:{margin:"14px 0",padding:18,borderRadius:18,border:"1px solid #223149",background:"#111a27",display:"grid",gap:8},scroll:{overflowX:"auto"}};
